name: Test AWS OIDC

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  test-aws-login:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6.2.3
        with:
          role-to-assume: arn:aws:iam::029633610686:role/github-actions-aws-de-demo
          aws-region: us-east-2

      - name: Verify AWS identity
        run: aws sts get-caller-identity