name: Terraform CI/CD

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:

  # ==========================================================
  # VALIDATE
  # Runs for PRs, pushes, and manual runs
  # Does NOT access AWS
  # ==========================================================
  validate:
    name: Validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4.0.1
        with:
          terraform_version: 1.13.4

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Validate Python Syntax
        run: python -m py_compile scripts/*.py


  # ==========================================================
  # PLAN
  # Runs after a push to main or a manual workflow run
  # Uses GitHub OIDC -> AWS temporary credentials
  # ==========================================================
  plan:
    name: Terraform Plan
    needs: validate
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.2.3
        with:
          role-to-assume: arn:aws:iam::029633610686:role/github-actions-aws-de-demo
          aws-region: us-east-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4.0.1
        with:
          terraform_version: 1.13.4

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Plan
        run: terraform plan -input=false -no-color


  # ==========================================================
  # APPLY
  # ONLY runs when you manually click "Run workflow"
  # on the main branch
  # ==========================================================
  apply:
    name: Terraform Apply
    needs: plan

    if: >
      github.event_name == 'workflow_dispatch' &&
      github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.2.3
        with:
          role-to-assume: arn:aws:iam::029633610686:role/github-actions-aws-de-demo
          aws-region: us-east-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4.0.1
        with:
          terraform_version: 1.13.4

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Plan
        run: terraform plan -input=false -out=tfplan

      - name: Terraform Apply
        run: terraform apply -input=false -auto-approve tfplan